apiVersion: v1
kind: ResourceQuota
metadata:
  name: montecarlo-resourcequota
spec:
  hard:
    limits.cpu: "4"
    limits.memory: "1Gi"
    #limits.memory: "2Gi"
    #limits.memory: "2Gi"
    #requests.cpu: "1"
    #requests.memory: "512Mi"
    pods: "10"
